import type { Metadata } from 'next';
import './globals.css';

import { IBM_Plex_Sans_KR, IBM_Plex_Sans, IBM_Plex_Sans_JP } from 'next/font/google';

const ibmKr = IBM_Plex_Sans_KR({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const ibmEn = IBM_Plex_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const ibmJa = IBM_Plex_Sans_JP({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmKr.className} ${ibmEn.className} ${ibmJa.className}`}>{children}</body>
    </html>
  );
}
